# Generated by Django 2.2.6 on 2019-10-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
